### ISSUE TITLE
Question: CaseInsensitive NotEqual

### ISSUE THREAD

**Issue by bpkinez** [bbartels/Delve#1]
Hi Benjamin,

thanks for awesome and useful library. It is exactly that I was looking for to implement in my REST APIs. 

Do you have plan to implement CaseInsensitive NotEqual `!=*` operator?

Thanks,
Branislav

**Comment by bbartels** [comment]
Fixed in [70ebf27](https://github.com/bbartels/Delve/commit/70ebf275dc770ee7e64c81219715a7dc684229cb).
