### ISSUE TITLE
Question: AddDefaultExpand method

### ISSUE THREAD

**Issue by bpkinez** [bbartels/Delve#10]
Hi Benjamin,

have you thought about adding `AddDefaultExpand` method to `QueryValidator` where navigation property will be loaded by default because now is `null`. E.g. for class `User`:
```cs
public class User
{
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public DateTime DateOfBirth { get; set; }

    public IEnumerable<UserRole> UserRoles { get; set; }
}
```

`UserRoles`  property is `null`, but with setting `AddDefaultExpand(x => x.UserRoles)` or `AddDefaultExpand(x => x.UserRoles.Select(ur => ur.Role))`, `UserRoles` property  or `UserRoles` with `Roles` will be populated.

**Comment by bbartels** [comment]
Thanks for the suggestion, I will have a look after the weekend!

**Comment by bpkinez** [comment]
Thank you very much for this upgrade!

BR,
Branislav
