### ISSUE TITLE
filters on json documents in SQL Server

### ISSUE THREAD

**Issue by gopala000** [bbartels/Delve#14]
I use SQL 2017 to store json documents and need to pass filters from API to apply on json properties. I also need projection to return only necessary properties and pagination. Does this library support querying on json documents or is there any modifications needed to make it work?

**Comment by bbartels** [comment]
This is an ORM dependent issue, if an ORM exists that correctly maps those json documents to c# classes then it will very well work. As far as I know EF Core does not currently support that, see here: https://github.com/aspnet/EntityFrameworkCore/issues/4021.
