### ISSUE TITLE
Bug: X-Pagination nextPageLink

### ISSUE THREAD

**Issue by bpkinez** [bbartels/Delve#2]
Hi Benjamin,

when I send request e.g. `http://localhost:51607/api/user?filter=FirstName!=Veronica`, I noticed that library is generating X-Pagination nextPageLink as `http://localhost:51607/api/User?pageNumber=2&pageSize=5&filter=FirstName!%3Dveronica` with `%3D` instead of `=` character. 

It would be nice when characters would not be URL encoded (Percent Encoded).

Thanks,
Branislav

**Comment by bbartels** [comment]
I wondered about this as well, but could not find a satisfying answer online on how to go about fixing it.
I have a suspicion it is linked to this [github issue](https://github.com/aspnet/Home/issues/2669).
I might just add some middle-ware that replaces the percent-encoded characters after generation.

**Comment by bpkinez** [comment]
Custom middleware seems to me a good temporary fix to this issue.

Thanks.

**Comment by bbartels** [comment]
Fixed in [7a45091](https://github.com/bbartels/Delve/commit/7a450918bed6a295e884274e217a4b68482d09a3).
