### ISSUE TITLE
Question: Default sort property

### ISSUE THREAD

**Issue by bpkinez** [bbartels/Delve#7]
Hi Benjamin,

what you think about adding method in `AbstractQueryValidator` to set certain property as default sort property if we don't want to sort results by primary key 'Id' by default:

```cs
public class UserQueryValidator : AbstractQueryValidator<User>
{
    public UserQueryValidator()
    {
        SetDefaultSortProperty("FirstName", x => x.FirstName, descending: true, order: 1);
        SetDefaultSortProperty("LastName", x => x.LastName, descending: false, order: 2);
    }
}
```
or to go with custom property attribute:

```cs
    public class User
    {
        public int Id { get; set; }

        [DefaultSortProperty(descending = true, order = 1)]
        public string FirstName { get; set; }

        [DefaultSortProperty(descending = false, order = 2)]
        public string LastName { get; set; }
        public DateTime DateOfBirth { get; set; }
    }
```
If we have two or more default order properties it will pick up first by lowest order number and sort result by that property.

**Comment by bbartels** [comment]
Good idea, I am working on a couple of things concerning defaults of ordering/sorting. Trying to get them out later today. I will try to include your suggestion.

**Comment by bbartels** [comment]
Added sorting/filtering/selecting defaults in [d6b3d8e](https://github.com/bbartels/Delve/commit/d6b3d8e55f28b11b806ceb727f176d4672f385ab).
